name: Check New Users
on:
  schedule:
    - cron: '0 * * * *'  # Hourly

jobs:
  check-users:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          npm install
          MODE=create node test.js
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}

      on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Hourly run