name: Run Node.js Script with Google Cloud Authentication

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install --verbose
          # Check if dotenv is in node_modules
          ls -l node_modules | grep dotenv

      # Step 4: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS path: $HOME/gcp-key.json"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-key.json

      # Step 5: Debug Google Credentials
      - name: Debug Google Credentials
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS path: $GOOGLE_APPLICATION_CREDENTIALS"
          ls -l $GOOGLE_APPLICATION_CREDENTIALS

      # Step 6: Run the Node.js script
      - name: Run the Node.js script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-key.json
        run: node test.js